version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=/api
    volumes:
#      - ./frontend:/app
      - /app/node_modules
    networks:
      - zkkyc-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:stable-alpine3.21
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
#      - backend
    networks:
      - zkkyc-network

volumes:
  postgres-data:

networks:
  zkkyc-network:
    driver: bridge